### ISSUE TITLE
一个博客的诞生 | sunhapper的博客

### ISSUE THREAD

**Issue by sunhapper** [sunhapper/sunhapper.github.io#1]
http://blog.sunhapper.tk/sync/yi-ge-bo-ke-de-dan-sheng/ 

 之前的博客都是记录在简书，偶尔有些零散的文章会往掘金和CSDN发一发，虽然这些平台写作体验还是挺不错的，不用考虑推广也有一些流量，但是前段时间简书整顿了一波，有几篇文章无辜被锁，觉得很恼火。  而且个人感觉简书文章含金量越来越低，推荐的文章

**Comment by sunhapper** [comment]
评论测试

**Comment by shaobin0604** [comment]
:-)
